### ISSUE TITLE
don't cause streams1 mode

### ISSUE THREAD

**Issue by juliangruber** [deoxxa/duplexer2#2]
this module is listening for `readable`'s `data` event and thus turns it into a streams1 stream. would be nice if it would leave them as streams2 streams.

**Comment by shinnn** [comment]
Fixed in https://github.com/deoxxa/duplexer2/pull/6 and released as [v0.1.0](https://github.com/deoxxa/duplexer2/commit/af38f7b1229d53e343bc65a13c1fc780ea5c9178).
