### ISSUE TITLE
0.1.3 breaks stream-combiner2 1.1.1

### ISSUE THREAD

**Issue by jeffcharles** [deoxxa/duplexer2#21]
Hi, we have a build process that uses grunt-contrib-imagemin to shrink a png file. We started getting build failures this morning with an error of `Fatal error: Cannot read property 'contents' of undefined`.

After some investigation, I noticed that when I force a dependency on 0.1.2 of duplexer2 in `stream-combiner2` the build works but when I have `stream-combiner2` use version 0.1.3 or 0.1.4 of duplexer2, the build fails with the same error. This leads me to suspect something in 0.1.3 breaks `stream-combiner2` at 1.1.1.

**Comment by zertosh** [comment]
Fixed by https://github.com/gruntjs/grunt-contrib-imagemin/pull/329
