### ISSUE TITLE
Http response stales

### ISSUE THREAD

**Issue by ataube** [deoxxa/duplexer2#26]
I initially addressed this issue here: https://github.com/juliangruber/multipipe/issues/38 and it seems like duplexer2 is causing it...

Anyhow, I would like to use duplexer in a http server context doing something like this:

```
const express = require('express');
const JSONStream = require('JSONStream');
const duplex = require('duplexer2');
const app = express();

app.post('/duplexer', (req, res, next) => {
  const parse = JSONStream.parse()
  const stringify = JSONStream.stringify(false)
  const pipeline = duplex(parse, stringify)
  
  req.pipe(pipeline).pipe(res); // does not work, no response from the server
  // req.pipe(parse).pipe(stringify).pipe(res); // works
});

app.listen(3000, () => {
  console.log('Server started...')
});
```
Does anybody maybe have an idea what the reason of this could be? It feels like the response writer is waiting for the request to terminate or the other way around but this just never happens...

**Comment by deoxxa** [comment]
I'm not 100% sure what your goal is, but it doesn't look like you've got the two halves of your duplex stream connected at all, so this all makes sense.

Maybe you want something like https://www.npmjs.com/package/bun instead, given that you've named your duplex stream "pipeline".

**Comment by juliangruber** [comment]
yeah, there should be `parse.pipe(stringify)` after your pipeline definition

**Comment by ataube** [comment]
Thanks for pointing this out, I didn't think about connection the two halves of the duplex stream, somehow I assumed this is done behind the scenes. And bun is exactly what I was looking for.
