### ISSUE TITLE
Change version to at least 0.1.0

### ISSUE THREAD

**Issue by appden** [deoxxa/duplexer2#9]
This module is great. The problem is that when dependents do `npm install duplexer2 --save` and they get `^0.0.2` in their package.json, they will be pinned to exactly that version. I believe @substack experienced this exact frustration with this package awhile ago when it was updated from `0.0.1`.

**Comment by iegik** [comment]
```
npm ERR! missing: readable-stream@~1.1.9, required by duplexer2@0.0.2
```

**Comment by shinnn** [comment]
Fixed. https://github.com/deoxxa/duplexer2/commit/af38f7b1229d53e343bc65a13c1fc780ea5c9178
